# Generated by Django 5.2.4 on 2025-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shop_shop_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name',
            new_name='branch_name',
        ),
        migrations.AddField(
            model_name='branch',
            name='employee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
