# Generated by Django 5.2.4 on 2025-09-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_shopmembership_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopmembership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='branch',
            name='employees',
        ),
        migrations.AlterField(
            model_name='branch',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.shop'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.shop'),
        ),
        migrations.AlterField(
            model_name='shopmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shopmembership',
            unique_together={('user', 'shop', 'branch')},
        ),
    ]
