# Generated by Django 5.2.4 on 2025-09-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_shopmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
    ]
